#!/bin/sh
set -e

echo resolver $(awk 'BEGIN{ORS=" "} $1=="nameserver" {if ($2 ~ /:/) print "["$2"]"; else print $2}' /etc/resolv.conf) ";" > /etc/nginx/resolvers.conf

# MLRUN_IGZ_UI_ALLOWED_ORIGIN is only set by mlefi when this container is
# deployed as an igz4-ui (oris-ui) Module Federation remote. When unset,
# this is a plain igz3 / CE deployment that proxies its own API calls.
if [ -n "${MLRUN_IGZ_UI_ALLOWED_ORIGIN}" ]; then
  NGINX_CONF_SRC=/etc/nginx/conf.d/nginx-mf.conf.tmpl
  ENVSUBST_VARS='${MLRUN_IGZ_UI_ALLOWED_ORIGIN}'
  sed -i 's|<base href="/mlrun/"|<base href="/projects/"|' /usr/share/nginx/html/index.html
else
  NGINX_CONF_SRC=/etc/nginx/conf.d/nginx.conf.tmpl
  ENVSUBST_VARS='${MLRUN_API_PROXY_URL} \
          ${MLRUN_FUNCTION_CATALOG_URL} \
          ${MLRUN_FUNCTION_CATALOG_PATH} \
          ${MLRUN_NUCLIO_API_URL} \
          ${MLRUN_V3IO_ACCESS_KEY}'

  envsubst '${MLRUN_BETA_MODE} \
            ${MLRUN_NUCLIO_MODE} \
            ${MLRUN_NUCLIO_UI_URL}' \
  < /usr/share/nginx/html/config.json.tmpl \
  > /usr/share/nginx/html/config.json
fi

envsubst "$ENVSUBST_VARS" \
< "$NGINX_CONF_SRC" \
> /etc/nginx/conf.d/nginx.conf

nginx -t
exec nginx -g 'daemon off;'
